{
 "title": "payment-api/RED",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "description": "Запросов в секунду по путям. RED: Rate",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_requests_total{job=\"payment-api\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\r\n  sum(rate(http_requests_total{job=\"payment-api\", status!~\"5..\"}[5m]))\r\n  /\r\n  sum(rate(http_requests_total{job=\"payment-api\"}[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path) (rate(http_request_duration_seconds_bucket{job=\"payment-api\"}[5m])))",
     "legendFormat": "p95 {{path}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le, path) (rate(http_request_duration_seconds_bucket{job=\"payment-api\"}[5m])))",
     "legendFormat": "p50 {{path}}"
    }
   ]
  }
 ]
}