prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 15s
    evaluationInterval: 15s

    
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 2Gi

grafana:
  enabled: true
  adminPassword: admin
  service:
    type: ClusterIP

alertmanager:
  enabled: true

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
