{
 "title": "SLO",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Availability (1h)",
   "type": "stat",
   "description": "slo",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sli:payment_api_availability:ratio_rate1h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Remaining (30d)",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\r\n  1 - (\r\n    (1 - (\r\n      sum(increase(http_requests_total{job=\"payment-api\", path!~\"/healthz|/readyz\", status!~\"5..\"}[30d]))\r\n      /\r\n      sum(increase(http_requests_total{job=\"payment-api\", path!~\"/healthz|/readyz\"}[30d]))\r\n    ))\r\n    / 0.005\r\n  )\r\n, 1)",
     "legendFormat": "{{Error Budget Remaining (30d)}}"
    }
   ]
  },
  {
   "title": "Error Budget Burn Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(1 - sli:payment_api_availability:ratio_rate1h) / 0.005",
     "legendFormat": "{{burn_rate_1h}}"
    },
    {
     "expr": "(1 - sli:payment_api_availability:ratio_rate6h) / 0.005",
     "legendFormat": "{{burn_rate_6h}}"
    }
   ]
  }
 ]
}