apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: banking
  labels:
    app: payment-api
    tier: critical          # позже по этому лейблу будем роутить алерты
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
        tier: critical
      annotations:
        # Эти аннотации прочитает vmagent на следующей смене
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: payment-api
          image: payment-api:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: SERVICE_NAME
              value: payment-api
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 256Mi
          livenessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /readyz, port: 8000 }
            initialDelaySeconds: 3
            periodSeconds: 5
